<?php
  include "assets/header.php";
?>
    <div class="container">
      <div class="m-4 text-center">
        <h2>Introduction</h2>
      </div>
      <p>
        The classical journey to EBC starts by flying from Kathmandu to Lukla, then you pick up the hiking trails from there. The 88km/55ml hiking trip takes a minimum of 12 days to complete: going up to EBC in eight days (including two days for acclimating) and coming down to Lukla then flying back to Kathmandu in four days (including spending one night in Lukla – all flights leave in the morning). However, many hikers take a half-day bus ride from Kathmandu to Jiri, then hike four days to Lukla, to pick up the EBC trail. In this way, the journey will take a minimum of 20 days. People would rather spend 8 extra days going via Jiri to avoid using the scary and unreliable Lukla airport - more will follow.

        <br /><br />
        The trails to EBC are mostly uneven and unpaved, narrow here and wide there; although many sections are steep, no ropes or technical climb skills are required. The trails were formed naturally with many twists and turns, but it is reasonable to believe one is not likely to get lost. Hikers, porters, and convoys of transportation animals (mainly yaks and horses) share the trail. Steps are being built in certain parts of the trails, and in one section the animal traffic has been separated from hikers. At above 3,500-4,000m/11,500-13,000ft levels, vegetation, and farmland are thinning out and disappearing. The dirt roads are dusty on a clear day with frequent gusts of mountain winds and are muddy, mixed with animal dumps, in rain and snow. The trails are the only means to reach Everest Base Camp other than by helicopter. Even those Mountaineers would have to take the same hiking trails to the base camp: If they fly directly from Kathmandu, which is at an elevation of 1,300m/4,200ft, to EBC of 5,364m/17,598ft, without proper acclimatization they would suffer serious high-altitude sickness which could be fatal.

        <br /><br />
        All the provisions to sustain modern life in the mountains are brought up by porters and animals. On the trails many porters are carrying a weight of the minimum of 60kg/130 lb, heavier than their body weight; their force and mental toughness are second to none. The higher the altitude the more expensive the goods. A bottle of water costing $0.5 in Kathmandu could sell for $3 or $5 in high elevation; charging a phone or a power bank could set you back $5-10. But few would ever complain. Any grievance would dissipate when the thoughts come to mind of how the porters have struggled to bring goods to the mountains.

        <br /><br />
        The vertical distance from Lukla to EBC is 2,800m/9,200ft; but the ups and downs of the trails would multiply that by many times when you reach EBC. The higher you go the colder the weather (temperature drops 9.8C for every 1,000m up or 5.4F/1,000ft). In March at Lukla the daytime temperature is in the low single digits; at night it’s below freezing. At above 4,000-5,000m/13,100-16,500ft, it is below freezing during the day and could reach minus 10-20C/14-negative 4F at night.

        <br /><br />
        In high mountains, houses are erected when a piece of relatively flat spot is found, thus they would not necessarily face the south to capture sunlight and heat during the day. Due to the cost of transportation, houses are not insulated, and cracks and gaps in the exterior walls and window frames are visible. Since there is no indoor heating, after sunset the temperatures are similar inside and outside the guest houses (called “teahouses” by hikers). On this trip, the night temperature inside every teahouse had been below freezing every night.

        <br /><br />
        There are usually two single beds in a guestroom with no private bath (there are apparently many exceptions). Public bathrooms are in the corridor, also not heated. There is always a public space doubling as a dining room, and a small fire would be built after sunset. But due to fuel shortage, even in this “heated” room one still needs to dress warmly at all times.

        <br><br>
        Nepal has abundant water resources, but most of the streams are permanently frozen in high mountains, so little hydropower can be harvested. Electricity is generated by rooftop solar and stored in batteries, which are reserved primarily for lighting. To conserve energy, a fee would be imposed to charge a phone; however, most locations, including the village next to the base camp, do not have cell signals.

        <br />
      </p>
      <div class="m-2 text-center">
        <a
          href="itinerary-e.php"
          class="btn btn-outline-success outline-double rounded-pill mx-1 py-0 fw-bold"
          
          >Itinerary &#8811</a
        >
        <a
          <a
          href="index.php"
          class="btn btn-outline-success outline-double rounded-pill mx-1 py-0 fw-bold"
          >Index</a
        >
      </div>
    </div>
<?php
  include "assets/footer.php";
?>